jobs:
  - job: publish_pipeline
    displayName: Publish Pipeline

    variables:
      - template: ./variables.yml

    steps:
      - task: UsePythonVersion@0
        displayName: Use Python 3.7.*
        inputs:
          versionSpec: 3.7.*

      - task: Bash@3
        displayName: Install Dependencies
        inputs:
          targetType: "inline"
          script: |
            pip3 install -r $(dependencies_test)

      - task: DownloadBuildArtifacts@0
        displayName: Download Model Metadata Artifact
        inputs:
          source: current
          artifactName: model-metadata
          downloadPath: $(Pipeline.Workspace)

      - task: AzureCLI@2
        displayName: Publish Pipeline to Workspace
        inputs:
          scriptType: bash
          azureSubscription: $(service_connection)
          scriptLocation: inlineScript
          inlineScript: |
            export SUBSCRIPTION_ID=$(az account show | jq ".id" --raw-output)

            export MODEL_ID=$(cat $(Pipeline.Workspace)/model-metadata/model.json | jq ".modelId" --raw-output)

            export APPLICATION_INSIGHTS_CONNECTION_STRING=$(az resource show \
            --resource-group $(resource_group_name) \
            --name $(application_insights_name) \
            --resource-type Microsoft.Insights/components \
            | jq ".properties.ConnectionString" --raw-output)

            python3 src/publish_batch_pipeline.py \
            --subscription_id $SUBSCRIPTION_ID \
            --resource_group $(resource_group_name) \
            --workspace_name $(workspace_name) \
            --compute_name $(compute_name) \
            --environment_specification $(dependencies_score) \
            --model_id $MODEL_ID \
            --pipeline_name $(pipeline_endpoint_name) \
            --pipeline_version $(Build.BuildId) \
            --input_dataset_name $(input_dataset_name) \
            --output_datastore_name $(output_datastore_name) \
            --ai_connection_string $APPLICATION_INSIGHTS_CONNECTION_STRING \
            --pipeline_metadata_file pipeline.json

            ls

      - task: PublishBuildArtifacts@1
        displayName: Publish Pipeline Metadata Artifact
        inputs:
          pathToPublish: $(System.DefaultWorkingDirectory)/pipeline.json
          artifactName: pipeline-metadata
