name: build_release - $(SourceBranchName) - $(Date:yyyyMMdd)$(Rev:.r) -
pool:
  vmImage: ubuntu-latest

variables:
  - template: ./templates/variables.yml

trigger:
  branches:
    include:
      - master
    exclude:
      - docs/*
      - LICENSE
      - README.md

stages:
  - stage: model_build
    displayName: Model Build
    jobs:
      # - template: ./templates/code-quality.yml
      # - template: ./templates/train.yml
      # - template: ./templates/register.yml
      - template: ./templates/publish.yml

  - stage: deploy_production
    displayName: Production Deployment
    dependsOn: model_build
    jobs:
      - deployment: Approval
        displayName: Production Deployment Approval
        environment: Production
      - template: ./templates/publish.yml
      - template: ./templates/schedule.yml
