parallel_run_config:
  input_format:
  mini_batch_size: 100
  error_threshold: 10
  output_action: append_row
  logging_level: INFO
  compute_target_name: cpu-cluster
  node_count: 1
  process_count_per_node: 1
  entry_script: score.py
  source_directory: src
  description: Batch scoring for credit risk model
  run_invocation_timeout: 60
  environment_name: score_env
  environment_dir_path: configuration/score.runconfig
