Schedule:
  description: "Change-Based Schedule"
  recurrence: ~
  pipeline_parameters:
    model_id: cardiovascular-disease-model:1
  wait_for_provisioning: True
  wait_timeout: 3600
  datastore_name: "schedule_datastore_name"
  polling_interval: 5
  data_path_parameter_name: ""
  continue_on_step_failure: None
  path_on_datastore: "cardiovascular_disease"
